const { createSlice } = require("@reduxjs/toolkit");
const { cakeActions } = require("../cake/cakeSlice");

const initialState ={
    numOfIceCream: 20,
};

const icecreamSlice = createSlice({
    name: 'icecream',
    initialState,
    reducers: {
        ordered: (state) => {
            state.numOfIceCream--
        },
        restocked: (state,action) => {
            state.numOfIceCream += action.payload
        },
    },
    // extraReducers: {
    //     ['cake/ordered']: (state) => { //the 'cake' is gotten from the reducer name and the 'ordered' is gotten from the reducer action
    //         state.numOfIceCream--
    //     }, // now whenever a cake is ordered, both the cake and ice cream count decrement by 1
    // },
    extraReducers: (builder) => {
        builder.addCase(cakeActions.ordered, state => {
            state.numOfIceCream--
        })
    }
});

module.exports = icecreamSlice.reducer;
module.exports.icecreamActions = icecreamSlice.actions;
//extra reducers are additional reducers apart from the reducer generated by createSlice